### PR TITLE
feat(content): Improve scannability with punctuation symbols in headings

### PR DESCRIPTION
**Pull request by vsrixyz**
## Description

This was a request by the localization team. I have added the punctuation symbol to each heading so it's more easily scanned. My initial impulse is to put the symbol in parentheses, but I am open to other design solutions!

## Checklist

- [x] :ok_hand: website updates are Garden Designer approved (add the designer as a reviewer)
- [x] :black_nib: copy updates are approved (add the content strategist as a reviewer)

### CODE REVIEW

**Review by hzhu — APPROVED** [review]
LGTM

**Review by jzempel — COMMENTED** [review]
@vsrixyz are you concerned about the impact to in-page permalinks? Also, the parenthesis parentheses feels weird. Not sure I’m feeling this direction.

**Review by ginnywood — APPROVED** [review]
Punchy but effective for the goal of scannability.
One alternative I can think of is including the punctuation mark below the header. But that would be more subtle—maybe too subtle. I think this works.

**Comment by jzempel** [comment]
The experts have spoken. 🙌 Thanks y'all.

**Comment by allisonacs** [comment]
Y'all, sorry for opening a can of worms, but this does not meet visual design standards, and I'd like to see this rolled back. We can do better while still improving our users' ability to find what they're looking for.

**Pull request merged**
