### PR TITLE
chore: add menu deps to dropdown

### PR DESCRIPTION
**Pull request by rossmoody**
## Description

**Fix Jira [GARDEN]1377**
All "Dropdown" pages now include the same available Menu/Item exports 

## Checklist

- [ ] :ok_hand: website updates are Garden Designer approved (add the designer as a reviewer)
- [ ] :black_nib: copy updates are approved (add the content strategist as a reviewer)
- [ ] :wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver
- [ ] :zap: audited via [web.dev](https://web.dev/measure/) for performance and SEO
- [ ] :memo: tested in Chrome, Firefox, Safari, Edge, and IE11

### CODE REVIEW

**Comment by rossmoody** [comment]
@jzempel I agree

**Comment by austin94** [comment]
With `Autocomplete`, `Menu`, `Select`, and `Multiselect` now being on unique pages I see some improvement with this change. Before this change I'm not sure how someone going directly to `Autocomplete` for example would know that they are able to include menu items such as `ItemMeta`, `MediaItem`, etc.

To help simplify we could remove the non-Item prop-sheets though. i.e. The `Autocomplete` wouldn't need to see `Select` and `Trigger`

**Comment by jzempel** [comment]
The only way the additions make sense to me is if we pull in corresponding examples that highlight expected `Menu` usage within the various components.

In other words, expecting the design/developer audience of users to pick up "I can use menu media items under a multiselect" through the subtlety of a long stack of imports and API prop sheets is not a high-quality Garden website experience. 

For now, I think the pages are best as-is.

**Comment by allisonacs** [comment]
+1 @jzempel. While I can understand the concern, I think adding these prop sheets with no context ultimately is less helpful. If we're really concerned that people will come to an autocomplete and be confused or miss out on capabilities not explicitly listed, I'd recommend we have a sentence/paragraph under the API header saying something like,

> Autocomplete is a type of dropdown. Learn more about Menu and Item capabilities and props on the Menu page.

And link to the menu page. 

But, I also think we could leave it as is.

**Comment by jzempel** [comment]
@rossmoody is your preference to explore adding Allison's suggested link or close this PR for now?

**Comment by rossmoody** [comment]
My preference would be to close this one

**Pull request closed without merging**
