### PR TITLE
fix(examples): menu and icon buttons

### PR DESCRIPTION
**Pull request by jzempel**
## Description

- Unless icon buttons have a tooltip, they should include an `aria-label`.
- Update split button examples to incorporate chevron rotation.
- Improve split button menu placement (should be `bottom-end`).
- Update menu examples to use chevron media buttons.
- Update menu-arrow example to use an icon button trigger.
- Add `Dropdown` prop sheet to the Menu component page.

## Checklist

- [x] :ok_hand: website updates are Garden Designer approved (add the designer as a reviewer)
- [ ] :black_nib: ~copy updates are approved (add the content strategist as a reviewer)~
- [x] :wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver
- [x] :zap: audited via [web.dev](https://web.dev/measure/) for performance and SEO
- [x] :memo: tested in Chrome, Firefox, Safari, Edge, and IE11

### CODE REVIEW

**Comment by allisonacs** [comment]
Looks like the disappearing menu bug is present here? 🤔 https://share.getcloudapp.com/6qu2ZJnK

**Comment by jzempel** [comment]
@allisonacs weird, I can't reproduce at the current deployment URL: https://5efa58f11010ba01a40a741b--zendeskgarden.netlify.app/components/menu#arrow

**Comment by jzempel** [comment]
Actually, I can reproduce by directly targeting the URL (or reloading the page after having navigated to the URL). @austin94 curious if you have any ideas on this one?

**Comment by jzempel** [comment]
Steps to reproduce:
- goto https://5efa58f11010ba01a40a741b--zendeskgarden.netlify.app/
- Use nav to arrive at `Select` page
**result** example `Select` components work as expected
- Now reload page or goto https://5efa58f11010ba01a40a741b--zendeskgarden.netlify.app/components/select
**result** example `Select` components auto-dismiss when opened

**Pull request merged**
