### PR TITLE
refactor: updates core views to use v9 components

### PR DESCRIPTION
**Pull request by geotrev**
## Description

Following the update of `react-theming` to `v9`, this PR elevates core views of the website to adopt needed `v9` components.

## Detail

Views affected are primarily those found in `src/components`, with some other small changes to keep the style of the site consistent with what's on `main`.

Updated component packages (not updated in submodule yet):
- buttons
- colorpickers
- forms
- grid
- notifications
- tooltips
- typography

The below component pages were removed (due to removed components, like `ButtonGroup`, which break the pages anyway):

- `/components/button-group`
- `/components/multi-thumb-range`

Page views resemble what's on `main` with the exception of custom color applications (to be addressed in a future PR). Note views/elements like: form inputs (search), buttons, tooltips, code blocks, toast notifications, and prop/config sheets on API docs.

Screenshot 2024-07-31 at 10 57 17 AM

Screenshot 2024-07-31 at 10 57 19 AM

Screenshot 2024-07-31 at 10 57 25 AM

Screenshot 2024-07-31 at 10 57 29 AM

Screenshot 2024-07-31 at 12 00 01 PM

Screenshot 2024-07-31 at 10 38 09 AM

Screenshot 2024-07-31 at 10 41 18 AM

Screenshot 2024-07-31 at 10 41 33 AM

Screenshot 2024-07-31 at 10 42 40 AM

Screenshot 2024-07-31 at 10 44 54 AM

### CODE REVIEW

**Review by ze-flo — APPROVED** [review]
Thanks for remembering to remove pages deprecated components. Great work! 💯

**Comment by ze-flo** [comment]
Bummer. Just noticed a TS error is causing tests to fail. Feel to merge once fixed.

**Comment by geotrev** [comment]
@ze-flo I noticed that as well. About to get that fixed!

**Comment by geotrev** [comment]
Pushed up fixes to the ColorSwatch and ColorSwatchDialog examples to satisfy linting. I more or less pulled over [the commit](https://github.com/zendeskgarden/website/commit/43511e55d94276ab320fc245695bcba0c68994bc) from `next-old` which applies breaking prop changes.

**Comment by jzempel** [comment]
@geotrev @ze-flo as the work progresses, please make a note to carefully follow the [migration guide](https://github.com/zendeskgarden/react-components/blob/next/docs/migration.md). I would've expected this PR to pick up deprecated `Grid` subcomponents, etc.

**Pull request merged**
