### PR TITLE
feat(components): update `dropdowns.legacy` to v9

### PR DESCRIPTION
**Pull request by ze-flo**
## Description

Updates `dropdowns.legacy` to v9.

## Checklist

- [ ] ~~:ok_hand: website updates are Garden Designer approved (add the designer as a reviewer)~~
- [ ] ~~:black_nib: copy updates are approved (add the content strategist as a reviewer)~~
- [ ] ~~:link: considered opportunities for adding cross-reference URLs (grep for keywords)~~
- [ ] ~~:wheelchair: analyzed via [axe](https://www.deque.com/axe/) and evaluated using VoiceOver~~
- [ ] ~~:memo: tested in Chrome, Firefox, Safari, Edge~~

### CODE REVIEW

**Comment by ze-flo** [comment]
Screenshot 2024-08-02 at 3 49 03 PM


Added the `deprecated` tag to the `Dropdowns` nav item. Two questions:
1. Should we rename to `Dropdowns Legacy`?
2. If we decide to keep the deprecated tag on `Dropdowns` (?Legacy) nav item, should we remove the redundant tags from subcomponents?

**Review by jzempel — CHANGES_REQUESTED** [review]
Ah, bummer. Sorry about all the extra work, but we should just delete the deprecated component pages in v9.

**Comment by jzempel** [comment]
...and strip the `[new]` tags from `Combobox` and `Menu`

**Comment by ze-flo** [comment]
> Ah, bummer. Sorry about all the extra work, but we should just delete the deprecated component pages in v9.

Should we update the [migration guide](https://github.com/zendeskgarden/react-components/blob/1c9eabbb12b41b420410c23f1b925b20202ba6d4/docs/migration.md?plain=1#L116) to let our users know that while we're still publishing `react-dropdown.legacy` for compatibility purposes, its documentation will only be available in the V8 version of the website?

**Comment by ze-flo** [comment]
Closing in favor of https://github.com/zendeskgarden/website/pull/611.

**Pull request closed without merging**
